2024-01-29 19:23:37,767 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Mon, 29 Jan 2024 19:23:37 +0000. Up 6.35 seconds.
2024-01-29 19:23:37,767 - main.py[DEBUG]: No kernel command line url found.
2024-01-29 19:23:37,767 - main.py[DEBUG]: Closing stdin.
2024-01-29 19:23:37,768 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-01-29 19:23:37,769 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-29 19:23:37,786 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-01-29 19:23:37,787 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-29 19:23:37,801 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-01-29 19:23:37,802 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-29 19:23:37,808 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-01-29 19:23:37,809 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-29 19:23:37,827 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-01-29 19:23:37,828 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-29 19:23:37,848 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-01-29 19:23:37,849 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-29 19:23:37,876 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-01-29 19:23:37,877 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-29 19:23:37,904 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-01-29 19:23:37,905 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-29 19:23:37,935 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-01-29 19:23:37,936 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-29 19:23:37,967 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-01-29 19:23:37,968 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-01-29 19:23:37,968 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-01-29 19:23:37,970 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-01-29 19:23:37,970 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-01-29 19:23:37,972 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-01-29 19:23:37,973 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-01-29 19:23:37,982 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-01-29 19:23:37,982 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-01-29 19:23:37,983 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-01-29 19:23:37,984 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-01-29 19:23:37,985 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:37,992 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:38,002 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-01-29 19:23:38,013 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-01-29 19:23:38,013 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-01-29 19:23:38,013 - stages.py[DEBUG]: no cache found
2024-01-29 19:23:38,014 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-01-29 19:23:38,014 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-01-29 19:23:38,058 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-29 19:23:38,058 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-01-29 19:23:38,089 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-01-29 19:23:38,090 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-01-29 19:23:38,090 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-01-29 19:23:38,090 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-01-29 19:23:38,090 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-01-29 19:23:38,090 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-01-29 19:23:38,090 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-01-29 19:23:38,090 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-01-29 19:23:38,091 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-01-29 19:23:38,091 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-01-29 19:23:38,091 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-01-29 19:23:38,091 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-01-29 19:23:38,091 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-01-29 19:23:38,091 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-01-29 19:23:38,091 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-01-29 19:23:38,092 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-01-29 19:23:38,103 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-01-29 19:23:38,104 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-01-29 19:23:38,104 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,112 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-01-29 19:23:38,112 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-01-29 19:23:38,113 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,124 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2435b) after 1 attempts
2024-01-29 19:23:38,125 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,134 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2024-01-29 19:23:38,135 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,144 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-01-29 19:23:38,144 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,155 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-01-29 19:23:38,155 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,164 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-01-29 19:23:38,164 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,167 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-01-29 19:23:38,167 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,173 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-01-29 19:23:38,173 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,176 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-01-29 19:23:38,176 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,184 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-01-29 19:23:38,185 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,187 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-01-29 19:23:38,188 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,190 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2024-01-29 19:23:38,191 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,194 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-01-29 19:23:38,194 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,202 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-01-29 19:23:38,203 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,215 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-01-29 19:23:38,216 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,224 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-01-29 19:23:38,224 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,228 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-01-29 19:23:38,228 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,242 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-01-29 19:23:38,243 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,248 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-01-29 19:23:38,248 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,262 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-01-29 19:23:38,264 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,272 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ (200, 230b) after 1 attempts
2024-01-29 19:23:38,272 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,275 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/ (200, 13b) after 1 attempts
2024-01-29 19:23:38,275 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/3.255.203.237' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/3.255.203.237', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,278 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/ipv4-associations/3.255.203.237 (200, 11b) after 1 attempts
2024-01-29 19:23:38,278 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,282 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/device-number (200, 1b) after 1 attempts
2024-01-29 19:23:38,282 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,292 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/interface-id (200, 21b) after 1 attempts
2024-01-29 19:23:38,293 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,295 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-hostname (200, 41b) after 1 attempts
2024-01-29 19:23:38,295 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,302 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/local-ipv4s (200, 11b) after 1 attempts
2024-01-29 19:23:38,302 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,305 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/mac (200, 17b) after 1 attempts
2024-01-29 19:23:38,305 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,312 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/owner-id (200, 12b) after 1 attempts
2024-01-29 19:23:38,313 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,322 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-hostname (200, 49b) after 1 attempts
2024-01-29 19:23:38,322 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,332 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/public-ipv4s (200, 13b) after 1 attempts
2024-01-29 19:23:38,333 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,342 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-group-ids (200, 41b) after 1 attempts
2024-01-29 19:23:38,343 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,346 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/security-groups (200, 74b) after 1 attempts
2024-01-29 19:23:38,346 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,348 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-id (200, 24b) after 1 attempts
2024-01-29 19:23:38,349 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,352 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2024-01-29 19:23:38,352 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,362 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-id (200, 21b) after 1 attempts
2024-01-29 19:23:38,363 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,366 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-01-29 19:23:38,366 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,372 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:5e:76:c1:0b:c1/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-01-29 19:23:38,373 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,375 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-01-29 19:23:38,376 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,379 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2024-01-29 19:23:38,379 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,392 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-01-29 19:23:38,393 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,395 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2024-01-29 19:23:38,396 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,398 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-01-29 19:23:38,398 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,412 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-01-29 19:23:38,413 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,416 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-01-29 19:23:38,416 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,422 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-01-29 19:23:38,423 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,425 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-01-29 19:23:38,425 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,428 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-01-29 19:23:38,428 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,433 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 41b) after 1 attempts
2024-01-29 19:23:38,433 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,437 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-01-29 19:23:38,438 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,440 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-01-29 19:23:38,440 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,443 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-01-29 19:23:38,443 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,452 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-01-29 19:23:38,453 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,455 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 41b) after 1 attempts
2024-01-29 19:23:38,456 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,459 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 11b) after 1 attempts
2024-01-29 19:23:38,459 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,472 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-01-29 19:23:38,472 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,478 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-01-29 19:23:38,478 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,492 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 49b) after 1 attempts
2024-01-29 19:23:38,493 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,495 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-01-29 19:23:38,495 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,502 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-01-29 19:23:38,503 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,505 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 74b) after 1 attempts
2024-01-29 19:23:38,506 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,512 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-01-29 19:23:38,512 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,515 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 475b) after 1 attempts
2024-01-29 19:23:38,515 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,522 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1163b) after 1 attempts
2024-01-29 19:23:38,522 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,525 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1483b) after 1 attempts
2024-01-29 19:23:38,525 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-29 19:23:38,527 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-01-29 19:23:38,528 - util.py[DEBUG]: Crawl of metadata service took 0.437 seconds
2024-01-29 19:23:38,531 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-01-29 19:23:38,532 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-01-29 19:23:38,533 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-01-29 19:23:38,534 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-01-29 19:23:38,535 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpk6gfk6i9) - w: [600] 12126 bytes/chars
2024-01-29 19:23:38,536 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpzgcbmful) - w: [644] 7984 bytes/chars
2024-01-29 19:23:38,536 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-01-29 19:23:38,536 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-01-29 19:23:38,537 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-29 19:23:38,537 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-29 19:23:38,537 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,564 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-29 19:23:38,565 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-29 19:23:38,565 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,568 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-29 19:23:38,569 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-29 19:23:38,569 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,582 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-29 19:23:38,582 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-29 19:23:38,582 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,588 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-29 19:23:38,588 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-29 19:23:38,588 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,591 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-29 19:23:38,591 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,591 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-29 19:23:38,602 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-01-29 19:23:38,602 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-02934d2a7fab7a2db'
2024-01-29 19:23:38,603 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db (recursive=True)
2024-01-29 19:23:38,609 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/handlers (recursive=False)
2024-01-29 19:23:38,610 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db (recursive=True)
2024-01-29 19:23:38,617 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/scripts (recursive=False)
2024-01-29 19:23:38,618 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db (recursive=True)
2024-01-29 19:23:38,637 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem (recursive=False)
2024-01-29 19:23:38,638 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-02934d2a7fab7a2db/datasource (quiet=False)
2024-01-29 19:23:38,638 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/datasource - wb: [644] 29 bytes
2024-01-29 19:23:38,639 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/datasource (recursive=False)
2024-01-29 19:23:38,640 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/datasource (recursive=False)
2024-01-29 19:23:38,641 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-01-29 19:23:38,641 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-01-29 19:23:38,642 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-01-29 19:23:38,643 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-01-29 19:23:38,643 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-01-29 19:23:38,643 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-01-29 19:23:38,644 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-01-29 19:23:38,645 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-01-29 19:23:38,646 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-01-29 19:23:38,646 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-01-29 19:23:38,647 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-01-29 19:23:38,647 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-01-29 19:23:38,648 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-01-29 19:23:38,649 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-01-29 19:23:38,650 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12620 bytes
2024-01-29 19:23:38,651 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/obj.pkl (recursive=False)
2024-01-29 19:23:38,662 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/obj.pkl (recursive=False)
2024-01-29 19:23:38,663 - main.py[DEBUG]: [net] init will now be targeting instance id: i-02934d2a7fab7a2db. new=True
2024-01-29 19:23:38,663 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-29 19:23:38,664 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-29 19:23:38,664 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,687 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-29 19:23:38,687 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-29 19:23:38,687 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,689 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-29 19:23:38,689 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-29 19:23:38,689 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,703 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-29 19:23:38,703 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-29 19:23:38,703 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,711 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-29 19:23:38,711 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-29 19:23:38,711 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,714 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-29 19:23:38,714 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,714 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-29 19:23:38,716 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-01-29 19:23:38,716 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-01-29 19:23:38,716 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-29 19:23:38,716 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-29 19:23:38,717 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-01-29 19:23:38,717 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-01-29 19:23:38,717 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-29 19:23:38,717 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-29 19:23:38,717 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-01-29 19:23:38,717 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-01-29 19:23:38,717 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-01-29 19:23:38,717 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-01-29 19:23:38,717 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-01-29 19:23:38,718 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-01-29 19:23:38,718 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-01-29 19:23:38,718 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-01-29 19:23:38,718 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-01-29 19:23:38,718 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-29 19:23:38,718 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-29 19:23:38,719 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-01-29 19:23:38,719 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-01-29 19:23:38,719 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-01-29 19:23:38,719 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-01-29 19:23:38,719 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-01-29 19:23:38,719 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-01-29 19:23:38,719 - stages.py[DEBUG]: network config disabled by system_cfg
2024-01-29 19:23:38,719 - stages.py[INFO]: network config is disabled by system_cfg
2024-01-29 19:23:38,719 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-01-29 19:23:38,719 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-01-29 19:23:38,719 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt - wb: [600] 2435 bytes
2024-01-29 19:23:38,720 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt (recursive=False)
2024-01-29 19:23:38,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt (recursive=False)
2024-01-29 19:23:38,734 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,738 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt.i - wb: [600] 2457 bytes
2024-01-29 19:23:38,739 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt.i (recursive=False)
2024-01-29 19:23:38,740 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/user-data.txt.i (recursive=False)
2024-01-29 19:23:38,741 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt - wb: [600] 0 bytes
2024-01-29 19:23:38,742 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt (recursive=False)
2024-01-29 19:23:38,743 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt (recursive=False)
2024-01-29 19:23:38,745 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt.i - wb: [600] 308 bytes
2024-01-29 19:23:38,746 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt.i (recursive=False)
2024-01-29 19:23:38,747 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data.txt.i (recursive=False)
2024-01-29 19:23:38,747 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt - wb: [600] 0 bytes
2024-01-29 19:23:38,748 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt (recursive=False)
2024-01-29 19:23:38,749 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt (recursive=False)
2024-01-29 19:23:38,751 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt.i - wb: [600] 308 bytes
2024-01-29 19:23:38,762 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt.i (recursive=False)
2024-01-29 19:23:38,763 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/vendor-data2.txt.i (recursive=False)
2024-01-29 19:23:38,764 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-29 19:23:38,766 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-4-50.eu-west-1.compute.internal (ip-172-31-4-50)
2024-01-29 19:23:38,766 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-4-50.eu-west-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:38,939 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-4-50.eu-west-1.compute.internal
2024-01-29 19:23:38,940 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-4-50.eu-west-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:38,947 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp1m81eq9i) - w: [644] 88 bytes/chars
2024-01-29 19:23:38,948 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/consume_data - wb: [644] 25 bytes
2024-01-29 19:23:38,949 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/consume_data (recursive=False)
2024-01-29 19:23:38,951 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/consume_data (recursive=False)
2024-01-29 19:23:38,962 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/consume_data'>)
2024-01-29 19:23:38,963 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-01-29 19:23:38,964 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-01-29 19:23:38,965 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-01-29 19:23:38,966 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-01-29 19:23:38,967 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-01-29 19:23:38,967 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:38,968 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-01-29 19:23:38,969 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-01-29 19:23:38,969 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-01-29 19:23:38,969 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1786 bytes
2024-01-29 19:23:38,970 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/scripts/user-data.txt (recursive=False)
2024-01-29 19:23:38,971 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/scripts/user-data.txt (recursive=False)
2024-01-29 19:23:38,972 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-01-29 19:23:38,973 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/cloud-config.txt - wb: [600] 154 bytes
2024-01-29 19:23:38,974 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/cloud-config.txt (recursive=False)
2024-01-29 19:23:38,975 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/cloud-config.txt (recursive=False)
2024-01-29 19:23:38,976 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,976 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,977 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-01-29 19:23:38,977 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-01-29 19:23:38,977 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-01-29 19:23:38,977 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-01-29 19:23:38,978 - stages.py[DEBUG]: no vendordata from datasource
2024-01-29 19:23:38,978 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-01-29 19:23:38,978 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-01-29 19:23:38,978 - stages.py[DEBUG]: no vendordata2 from datasource
2024-01-29 19:23:38,978 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-01-29 19:23:38,978 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-29 19:23:38,978 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-29 19:23:38,978 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,004 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-29 19:23:39,004 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-29 19:23:39,004 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,006 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-29 19:23:39,007 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-29 19:23:39,007 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,011 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-29 19:23:39,011 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-29 19:23:39,012 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,017 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-29 19:23:39,018 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-29 19:23:39,018 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,032 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-29 19:23:39,032 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,032 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-29 19:23:39,033 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-01-29 19:23:39,033 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-01-29 19:23:39,033 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,035 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,036 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,165 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-01-29 19:23:39,165 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-01-29 19:23:39,165 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-01-29 19:23:39,182 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-01-29 19:23:39,183 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16754 bytes
2024-01-29 19:23:39,185 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/obj.pkl (recursive=False)
2024-01-29 19:23:39,187 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/obj.pkl (recursive=False)
2024-01-29 19:23:39,188 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-01-29 19:23:39,188 - main.py[DEBUG]: no di_report found in config.
2024-01-29 19:23:39,190 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,191 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,202 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,202 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,211 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,211 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,215 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,215 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,221 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,222 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,225 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,225 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,243 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,244 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,249 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,249 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,252 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,253 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,261 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,262 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,265 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,265 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,268 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,268 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,282 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,282 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,286 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,287 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,291 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,292 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,302 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:39,302 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:39,306 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-29 19:23:39,307 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-01-29 19:23:39,307 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-01-29 19:23:39,307 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcd90>)
2024-01-29 19:23:39,307 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-01-29 19:23:39,308 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-01-29 19:23:39,308 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-01-29 19:23:39,308 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-01-29 19:23:39,308 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_seed_random - wb: [644] 25 bytes
2024-01-29 19:23:39,309 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_seed_random (recursive=False)
2024-01-29 19:23:39,311 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_seed_random (recursive=False)
2024-01-29 19:23:39,321 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_seed_random'>)
2024-01-29 19:23:39,322 - cc_seed_random.py[DEBUG]: no command provided
2024-01-29 19:23:39,322 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-01-29 19:23:39,322 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-01-29 19:23:39,323 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-01-29 19:23:39,323 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcd90>)
2024-01-29 19:23:39,323 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-01-29 19:23:39,324 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-01-29 19:23:39,325 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-01-29 19:23:39,325 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-01-29 19:23:39,325 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_files - wb: [644] 25 bytes
2024-01-29 19:23:39,326 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_files (recursive=False)
2024-01-29 19:23:39,328 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_files (recursive=False)
2024-01-29 19:23:39,330 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_files'>)
2024-01-29 19:23:39,330 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-01-29 19:23:39,330 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-01-29 19:23:39,330 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-01-29 19:23:39,330 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-01-29 19:23:39,330 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_metadata - wb: [644] 25 bytes
2024-01-29 19:23:39,331 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_metadata (recursive=False)
2024-01-29 19:23:39,335 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_metadata (recursive=False)
2024-01-29 19:23:39,336 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_write_metadata'>)
2024-01-29 19:23:39,336 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2024-01-29 19:23:39,340 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-01-29 19:23:39,341 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-01-29 19:23:39,342 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-01-29 19:23:39,342 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-01-29 19:23:39,343 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-01-29 19:23:39,343 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-01-29 19:23:39,351 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-01-29 19:23:39,352 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-01-29 19:23:39,352 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-01-29 19:23:39,352 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-01-29 19:23:39,352 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcfa0>)
2024-01-29 19:23:39,352 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-01-29 19:23:39,352 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,376 - util.py[DEBUG]: Reading from /proc/1450/mountinfo (quiet=False)
2024-01-29 19:23:39,376 - util.py[DEBUG]: Read 2928 bytes from /proc/1450/mountinfo
2024-01-29 19:23:39,377 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-01-29 19:23:39,377 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-01-29 19:23:39,377 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-01-29 19:23:39,377 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-01-29 19:23:39,378 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,496 - util.py[DEBUG]: resize_devices took 0.121 seconds
2024-01-29 19:23:39,496 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-01-29 19:23:39,496 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-01-29 19:23:39,496 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-01-29 19:23:39,497 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-01-29 19:23:39,497 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcd90>)
2024-01-29 19:23:39,497 - util.py[DEBUG]: Reading from /proc/1450/mountinfo (quiet=False)
2024-01-29 19:23:39,497 - util.py[DEBUG]: Read 2928 bytes from /proc/1450/mountinfo
2024-01-29 19:23:39,498 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-01-29 19:23:39,498 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-01-29 19:23:39,499 - util.py[DEBUG]: Forked child 1602 who will run callback log_time
2024-01-29 19:23:39,500 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-01-29 19:23:39,500 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,500 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-01-29 19:23:39,500 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-01-29 19:23:39,501 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-01-29 19:23:39,512 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_disk_setup - wb: [644] 25 bytes
2024-01-29 19:23:39,513 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_disk_setup (recursive=False)
2024-01-29 19:23:39,515 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_disk_setup (recursive=False)
2024-01-29 19:23:39,516 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_disk_setup'>)
2024-01-29 19:23:39,516 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-01-29 19:23:39,516 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-01-29 19:23:39,517 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-01-29 19:23:39,517 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_mounts - wb: [644] 25 bytes
2024-01-29 19:23:39,517 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_mounts (recursive=False)
2024-01-29 19:23:39,519 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_mounts (recursive=False)
2024-01-29 19:23:39,519 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_mounts'>)
2024-01-29 19:23:39,519 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-01-29 19:23:39,520 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-01-29 19:23:39,520 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-01-29 19:23:39,520 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-01-29 19:23:39,520 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: no need to setup swap
2024-01-29 19:23:39,520 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-01-29 19:23:39,521 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-01-29 19:23:39,521 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-01-29 19:23:39,521 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-01-29 19:23:39,521 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27c59d0>)
2024-01-29 19:23:39,532 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-01-29 19:23:39,532 - util.py[DEBUG]: Read 88 bytes from /var/lib/cloud/data/set-hostname
2024-01-29 19:23:39,532 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-01-29 19:23:39,532 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-01-29 19:23:39,533 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-01-29 19:23:39,533 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-01-29 19:23:39,533 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcd90>)
2024-01-29 19:23:39,533 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-4-50.eu-west-1.compute.internal (ip-172-31-4-50)
2024-01-29 19:23:39,533 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,537 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-4-50.eu-west-1.compute.internal in 1 files
2024-01-29 19:23:39,538 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 41 bytes
2024-01-29 19:23:39,539 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-01-29 19:23:39,539 - util.py[DEBUG]: backgrounded Resizing took 0.039 seconds
2024-01-29 19:23:39,540 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-01-29 19:23:39,541 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-01-29 19:23:39,541 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-01-29 19:23:39,542 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-01-29 19:23:39,542 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f09f27bcbe0>)
2024-01-29 19:23:39,542 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-01-29 19:23:39,542 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-01-29 19:23:39,542 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-01-29 19:23:39,542 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-01-29 19:23:39,543 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ca_certs - wb: [644] 25 bytes
2024-01-29 19:23:39,543 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ca_certs (recursive=False)
2024-01-29 19:23:39,545 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ca_certs (recursive=False)
2024-01-29 19:23:39,545 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ca_certs'>)
2024-01-29 19:23:39,545 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-01-29 19:23:39,545 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-01-29 19:23:39,546 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-01-29 19:23:39,546 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-01-29 19:23:39,546 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_rsyslog - wb: [644] 25 bytes
2024-01-29 19:23:39,547 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_rsyslog (recursive=False)
2024-01-29 19:23:39,548 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_rsyslog (recursive=False)
2024-01-29 19:23:39,549 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_rsyslog'>)
2024-01-29 19:23:39,549 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-01-29 19:23:39,549 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-01-29 19:23:39,549 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-01-29 19:23:39,549 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-01-29 19:23:39,549 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_selinux - wb: [644] 25 bytes
2024-01-29 19:23:39,550 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_selinux (recursive=False)
2024-01-29 19:23:39,572 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_selinux (recursive=False)
2024-01-29 19:23:39,572 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_selinux'>)
2024-01-29 19:23:39,580 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-01-29 19:23:39,581 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-01-29 19:23:39,581 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-01-29 19:23:39,581 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-01-29 19:23:39,581 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-01-29 19:23:39,581 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-01-29 19:23:39,581 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-01-29 19:23:39,592 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-01-29 19:23:39,592 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_users_groups - wb: [644] 25 bytes
2024-01-29 19:23:39,593 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_users_groups (recursive=False)
2024-01-29 19:23:39,595 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_users_groups (recursive=False)
2024-01-29 19:23:39,596 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_users_groups'>)
2024-01-29 19:23:39,597 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-01-29 19:23:39,597 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,641 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-01-29 19:23:39,642 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-01-29 19:23:39,643 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-01-29 19:23:39,644 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-01-29 19:23:39,652 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-01-29 19:23:39,653 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-01-29 19:23:39,653 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-01-29 19:23:39,653 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-01-29 19:23:39,654 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ssh - wb: [644] 22 bytes
2024-01-29 19:23:39,655 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ssh (recursive=False)
2024-01-29 19:23:39,656 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ssh (recursive=False)
2024-01-29 19:23:39,657 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ssh'>)
2024-01-29 19:23:39,658 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,686 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-01-29 19:23:39,712 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:39,734 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-01-29 19:23:39,753 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-01-29 19:23:39,753 - util.py[DEBUG]: Read 128 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-01-29 19:23:39,753 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-01-29 19:23:39,753 - util.py[DEBUG]: Read 208 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-01-29 19:23:39,754 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-29 19:23:39,754 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-29 19:23:39,756 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-01-29 19:23:39,756 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-01-29 19:23:39,757 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-29 19:23:39,757 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,758 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,758 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-01-29 19:23:39,758 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-01-29 19:23:39,758 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-01-29 19:23:39,758 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-29 19:23:39,758 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,759 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,759 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-01-29 19:23:39,771 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-29 19:23:39,772 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-29 19:23:39,774 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-01-29 19:23:39,778 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-29 19:23:39,778 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,779 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,779 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-01-29 19:23:39,779 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-01-29 19:23:39,779 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-01-29 19:23:39,779 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-29 19:23:39,780 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,780 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-29 19:23:39,780 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-01-29 19:23:39,792 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-01-29 19:23:39,792 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-01-29 19:23:39,793 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpyii5gsh6) - w: [644] 486 bytes/chars
2024-01-29 19:23:39,793 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-01-29 19:23:39,794 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-01-29 19:23:39,794 - util.py[DEBUG]: cloud-init mode 'init' took 2.245 seconds (2.25)
2024-01-29 19:23:39,794 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-01-29 19:23:40,906 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Mon, 29 Jan 2024 19:23:40 +0000. Up 9.39 seconds.
2024-01-29 19:23:40,916 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,916 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,931 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,932 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,935 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,936 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,942 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,942 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,947 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,948 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,962 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,962 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,967 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,968 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,981 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,982 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,985 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,985 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,988 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:40,988 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:40,990 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-29 19:23:41,002 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-01-29 19:23:41,002 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-01-29 19:23:41,002 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-01-29 19:23:41,003 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_keyboard - wb: [644] 25 bytes
2024-01-29 19:23:41,006 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_keyboard (recursive=False)
2024-01-29 19:23:41,010 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_keyboard (recursive=False)
2024-01-29 19:23:41,011 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_keyboard'>)
2024-01-29 19:23:41,011 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-01-29 19:23:41,011 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-01-29 19:23:41,011 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-01-29 19:23:41,012 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-01-29 19:23:41,012 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_locale - wb: [644] 25 bytes
2024-01-29 19:23:41,013 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_locale (recursive=False)
2024-01-29 19:23:41,014 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_locale (recursive=False)
2024-01-29 19:23:41,014 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_locale'>)
2024-01-29 19:23:41,015 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-01-29 19:23:41,015 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-01-29 19:23:41,015 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-01-29 19:23:41,015 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-01-29 19:23:41,015 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-01-29 19:23:41,015 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-01-29 19:23:41,019 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-01-29 19:23:41,022 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-01-29 19:23:41,023 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-01-29 19:23:41,023 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-01-29 19:23:41,023 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-01-29 19:23:41,023 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_set_passwords - wb: [644] 25 bytes
2024-01-29 19:23:41,024 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_set_passwords (recursive=False)
2024-01-29 19:23:41,025 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_set_passwords (recursive=False)
2024-01-29 19:23:41,026 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_set_passwords'>)
2024-01-29 19:23:41,026 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-01-29 19:23:41,059 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-29 19:23:41,059 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-29 19:23:41,060 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-01-29 19:23:41,060 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-01-29 19:23:41,060 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-01-29 19:23:41,060 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-01-29 19:23:41,061 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-01-29 19:23:41,061 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_variables - wb: [644] 25 bytes
2024-01-29 19:23:41,063 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_variables (recursive=False)
2024-01-29 19:23:41,064 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_variables (recursive=False)
2024-01-29 19:23:41,065 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_variables'>)
2024-01-29 19:23:41,065 - cc_yum_variables.py[INFO]: handling yum-variables
2024-01-29 19:23:41,065 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.3, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-01-29 19:23:41,065 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-01-29 19:23:41,065 - cc_yum_variables.py[INFO]: No yum vars to set
2024-01-29 19:23:41,065 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-01-29 19:23:41,065 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-01-29 19:23:41,066 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-01-29 19:23:41,066 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-01-29 19:23:41,067 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_add_repo (recursive=False)
2024-01-29 19:23:41,068 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_add_repo (recursive=False)
2024-01-29 19:23:41,069 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_yum_add_repo'>)
2024-01-29 19:23:41,069 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-01-29 19:23:41,069 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-01-29 19:23:41,069 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-01-29 19:23:41,069 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-01-29 19:23:41,069 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ntp - wb: [644] 25 bytes
2024-01-29 19:23:41,070 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ntp (recursive=False)
2024-01-29 19:23:41,081 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ntp (recursive=False)
2024-01-29 19:23:41,082 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_ntp'>)
2024-01-29 19:23:41,082 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-01-29 19:23:41,082 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-01-29 19:23:41,082 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-01-29 19:23:41,083 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-01-29 19:23:41,083 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_timezone - wb: [644] 25 bytes
2024-01-29 19:23:41,084 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_timezone (recursive=False)
2024-01-29 19:23:41,085 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_timezone (recursive=False)
2024-01-29 19:23:41,086 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_timezone'>)
2024-01-29 19:23:41,086 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-01-29 19:23:41,086 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-01-29 19:23:41,086 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-01-29 19:23:41,086 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-01-29 19:23:41,086 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f5596d7c340>)
2024-01-29 19:23:41,086 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-01-29 19:23:41,086 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-01-29 19:23:41,086 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-01-29 19:23:41,087 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-01-29 19:23:41,087 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_runcmd - wb: [644] 25 bytes
2024-01-29 19:23:41,088 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_runcmd (recursive=False)
2024-01-29 19:23:41,089 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_runcmd (recursive=False)
2024-01-29 19:23:41,089 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-02934d2a7fab7a2db/sem/config_runcmd'>)
2024-01-29 19:23:41,089 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-01-29 19:23:41,089 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-01-29 19:23:41,090 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-01-29 19:23:41,090 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp7v5nq1lr) - w: [644] 512 bytes/chars
2024-01-29 19:23:41,090 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-01-29 19:23:41,090 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-01-29 19:23:41,091 - util.py[DEBUG]: cloud-init mode 'modules' took 0.400 seconds (0.40)
2024-01-29 19:23:41,091 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-01-29 19:23:42,012 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Mon, 29 Jan 2024 19:23:41 +0000. Up 10.52 seconds.
2024-01-29 19:23:42,022 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-29 19:23:42,022 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-29 19:23:42,027 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-29 19:23:42,028 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-01-29 19:23:42,029 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-01-29 19:23:42,029 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f708a497e20>)
2024-01-29 19:23:42,029 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
